# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: root
  CLOUD_SQL_DATABASE_NAME: exdatabase
  CLOUD_SQL_CONNECTION_NAME: manifest-access-320809:us-central1:er-instance
# [END gae_python37_cloudsql_config]
